### ISSUE TITLE
[5] Wireframe of gadget store category

### ISSUE THREAD

**Issue by bloodline09** [janMaynard/Team-5#10]

**Comment by Bubs0220** [comment]
![Wireframe Reviews](https://user-images.githubusercontent.com/62087451/146561513-d0ad7ea3-dd90-4a0c-98ec-1cb0012c879f.png)
![Wireframe Gadgets](https://user-images.githubusercontent.com/62087451/146561518-3be37710-b9b6-4a96-90a8-61f923c3732f.png)

I give 5 points for the level of difficulty because we waited for the design of the other then we applied it to the wireframe we made
