### ISSUE TITLE
Food Store Logo

### ISSUE THREAD

**Issue by janMaynard** [janMaynard/Team-5#11]

**Comment by Nineteen89** [comment]
![20220201_111538_0000](https://user-images.githubusercontent.com/94513941/151967607-df681a22-4797-4a70-bdd1-daea18d4194f.png)
We made the food store logo in Canva and used a template for the look. After some consideration, we decided on the name Tea Express and used a color palette similar to the colors of milkteas. We give it 5 points for the difficulty because it is quite simple to do the design but challenging to choose between the drafts.
