### ISSUE TITLE
[8] Wireframe of register form (user and admin)

### ISSUE THREAD

**Issue by bloodline09** [janMaynard/Team-5#7]

**Comment by Nineteen89** [comment]
![user register wireframe](https://user-images.githubusercontent.com/94513941/153524942-03358f51-1fab-41d9-a579-312110fd844e.png)

We had done our wireframe on Cacoo.com by using the templates as our guide but we still started from scratch for this final output. At first we had also included the log in form but upon consultation with our teammates, it's been advised to remove it and just display the sign up form. Further improvements on the design led to this final output. We give 4 points for this because the design is easy to make but hard to conceptualize.

**Comment by LK-2nd** [comment]
![265034403_305963278092583_4889921524097010382_n](https://user-images.githubusercontent.com/94661861/146568305-cc830474-2c85-4cf8-89c7-6a38a6200b37.png)

We've relegate to make a wireframe of registration form for user and admin, at first I made my wireframe utilizing Lucidchart.com, we had remembered the log for structure for those user and admin who previously had an account, my plan was additionally easy. however, in the wake of having a conversation with our groupmates they recommended to focus on the registration form or sign up form for the user to create an account. Then, at that point, I've chosen to revamp my work on Cacoo.com, it is more better than the first one, we utilized the format as our aide. I gave 4 points for this as it was not a backbreaking yet in addition not that simple to have a thought.
